openapi: 3.0.3
info:
  title: API of klavogonki.ru
  description: API collected from known endpoints
  version: 0.0.1
servers:
  - url: http://klavogonki.ru/api/
    description: Main (production) server

# todo: also fill the KG's test server
  - url: http://test.klavogonki.ru/api
    description: Test server

##################### ПРОФИЛЬ ИГРОКА #####################

# биография, текущая машина итд
# GET /profile/get-summary?id=242585

# досье / сводка
# GET /profile/get-index-data?userId=242585

# бортжурнал
# sort=posts - сортировка по дате записи
# sort=comments - сортировка по комментариям

# showHidden=0 - не показывать скрытые записи ??? private only?
# showHidden=1 - показывать скрытые записи ??? private only?

# discussOnly=0 - показывать записи как с комментариями, так и без
# discussOnly=1 - показывать только с комментариями

# тип записи filter=achieve,record,car,voc,clubs,events,text_owner,text_other
# filter=achieve - достижения
# filter=record - рекорды
# filter=car - машины
# filter=voc - словари
# filter=clubs - клубы
# filter=events - события
# filter=text_owner - свои заметки
# filter=text_other - чужие заметки

# GET /profile/get-journal?id=242585

# GET /profile/get-journal?id=242585&limit=15&sort=comments&filter=achieve,record,car,voc,clubs,events,text_owner,text_other&showHidden=1&ignoreFriends=&discussOnly=0:

# пройденные достижения q=done
# GET /profile/get-achieves?q=done&sort=difficulty&userId=242585

# достижения в прогрессе
# sort=progress - сортировка "по прогрессу"
# sort=date - сортировка "по последнему обновлению"
# sort=difficulty - сортировка "по типу"
# GET /profile/get-achieves?q=progress&skip=0&sort=progress&userId=242585

# гараж (список машин)
# GET /profile/get-cars-list?userId=242585

# друзья. Вроде бы возвращает всех друзей, без всякого пейджинга.
# GET /profile/get-friends?userId=242585

# статистика - вроде бы все режимы
# GET /profile/get-stats-overview?userId=242585

# статистика по конкретному режиму
# gametype=normal - обычный
# gametype=marathon - марафон
# gametype=chars - буквы
# gametype=noerror - безошибочный
# gametype=digits - цифры
# gametype=sprint - спринт
# gametype=abra - абракадабра
# gametype=referats - Яндекс.Рефераты

# gametype=voc-13589 - кастомный словарь


# grouping=week - группировать по неделям
# grouping=day - группировать по дням
# grouping=none - группировать по "подробно" - доступно только в премиуме

# GET /profile/get-stats-details-data?userId=242585&gametype=normal&fromDate=2011-02-16&toDate=2020-12-15&grouping=week

##################### PROFILE - PRIVATE ONLY #####################
# {"err":"no auth"}, status 200
# GET /profile/get-private-prefs?id=242585

# сообщения
# GET /profile/get-messages-contacts:

# игнорируемые пользователи
# GET /profile/get-ignore-list

# выбрать машину
# POST /profile/select-car
# {"id":22} - payload

# обслуживание машины
# возвращает весь возможный набор тюнинга
# POST profile/view-car
# {"car":"18"} - payload

##################### СЛОВАРИ #####################
# Нет API, всё выдаётся прямо на странице?

##################### ИГРА #####################
# список данных
# http://klavogonki.ru/gamelist.data

# !! это не /api эндпойнт!
# получить задачи дня
# http://klavogonki.ru/views/partials/dlg-dailytask.html?bust=1601778366734

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

# todo: we need to try by hand for each parameter to identify whether it is mandatory
components:
  schemas:
    # todo: error model for
    # todo: list known errors:
# {"err":"no auth"}
# {"err":"invalid user id"} - пользователь не сущетсвует
# {"err":"hidden profile"} - скрытый профиль

# {"err":"permission blocked"} - например, запрос чужих данных, если статистика скрыта
# http://klavogonki.ru/api/profile/get-stats-details?userId=111001&gametype=voc-2 - возвращает "permission blocked", если статистика скрыта

# {"err":"invalid gametype"} - неправильный словарь
# http://klavogonki.ru/api/profile/get-stats-details?userId=242585&gametype=voc-8 - возвращает "invalid gametype", если у меня нет пробега по словарю

    # todo: most probably we should extend this (or probably use a string type instead) since requests also take gametype=voc-123
    # this is to document values for standard build-in dictionaries
    # see https://swagger.io/docs/specification/data-models/enums/
    StandardVocabulary:
      type: string
      enum:
        - normal # Обычный
        - marathon # Марафон
        - chars # Буквы
        - noerror # Безошибочный
        - digits # Цифры
        - sprint # Спринт
        - abra # Абракадабра
        - referats # Яндекс.Рефераты

